---
date: 2025-02-14
title: Неравенства Гельдера и Коши-Буняковского. Банаховы и Гильбертовы пространства
---

Вспомним определение нормы:

Норма в $X$: $||X|| \rightarrow \mathbb{C}\ (\mathbb{R})$

1.  $||k\cdot x|| = |k|\cdot ||x||, \quad k \in \mathbb{C}\ (\mathbb{R})$
2.  $|| x + y || \leq ||x|| + ||y||$
3.  $||x|| \geq 0, \quad ||x|| = 0 \Leftrightarrow x = 0$

Пример.

Пространство $l_n^p$

$$
\begin{aligned}
x = (x_1, ..., x_n) \\
||x||_p = \left( \sum_{i=1}^{n} |x_i|^p \right)^{1/p}
\end{aligned}
$$

При $p = 2$ получаем евклидову норму.

Пространство $l_n^\infty$:

$$
\begin{aligned}
||x||_\infty = \max_{1 \leq i \leq n} |x_i| \\
||x||_p \rightarrow ||x||_\infty \quad \text{при} \quad p \rightarrow \infty
\begin{end}
$$

Пространство функций:

$$
\begin{aligned}
L_p[a, b] \\
||f||_p = \left( \int_{a}^{b} |f(x)|^p dx \right)^{1/p}
\end{aligned}
$$

Свойства нормы можно переносить между разными p_1 и p_2.

$L^{p_1} \leftrightarrow L^{p_2}$

## Неравенство Гёльдера

### Сопряженные показатели
$$
\begin{aligned}
\frac{1}{p} + \frac{1}{q} = 1 \\
\end{aligned}
$$

Сопряженные показатели $p$ и $q$.

### Спомогательная лемма

$$
||fg||_1 \leq ||f||_p \cdot ||g||_q
$$

#### Доказательство леммы

Рассмотрим функцию $f(x) = x^m - mx$, при $x > 0, 0 <m <1$.

Возьмем производную:

$$
\begin{aligned}
f^\prime(x) = m(x^{m-1} - 1) \\
f^\prime(x) > 0, \quad x > 0 \Rightarrow
f(1) > f(x), \quad x > 0
\end{aligned}
$$

$$
1- m > x^m - mx \Rightarrow m(x-1) < x^m - 1
$$


### Неравенство Гёльдера

$$
\sum_{i=1}^{n} |a_i b_i| \leq \left( \sum_{i=1}^{n} |a_i|^p \right)^{1/p} \cdot \left( \sum_{i=1}^{n} |b_i|^q \right)^{1/q}
$$

Или в интегральной форме:

$$
\int_{a}^{b} |f(x)g(x)| dx \leq \left( \int_{a}^{b} |f(x)|^p dx \right)^{1/p} \cdot \left( \int_{a}^{b} |g(x)|^q dx \right)^{1/q}
$$

#### Доказательство неравенства Гёльдера

::: {.callout-warning}
TODO: Добавить доказательство
:::

::: {.callout-tip}
Причем здесь неравенство треугольника в $l^p$, $L^p$? См. К.А гл. IV параграф 5
:::

## Банаховы пространства

Нормированное линейное пространство $X$ называется банаховым, если оно полное относительно нормы.

$$
x_n \in X, {x_n} \text{ фундаментальна} \Rightarrow \exists x_0 \in X: ||x_n - x_0|| \rightarrow 0 \quad \text{при} \quad n \rightarrow \infty
$$

## Гильбертовы пространства

$H$ — гильбертово пространство, если

1.  $H$ — банахово пространство
2.  в $H$ определено скалярное произведение $(x, y)$

### Скалярное произведение

1. $(kx, y) = k(x, y)$
2. $(x_1 + x_2, y) = (x_1, y) + (x_2, y)$
3. $(x, y) = \overline{(y, x)}$ (комплексное сопряжение)
4. $(x, x) \geq 0, \quad (x, x) = 0 \Leftrightarrow x = 0$

### Следствие

Если у нас есть гильбертово пространство (в пространстве есть Скалярное произведение), то в нем можно ввести норму:

$$
||x|| = \sqrt{(x, x)}
$$

## Неравенство Коши-Буняковского

В любой гильбертовой пространстве выполнено неравенство Коши-Буняковского:

$$
(x, y)^2 \leq (x, x) \cdot (y, y)
$$ 

В частности, для $l^2$:

$$
(x, y) = \sum_{i=1}^{n} x_i y_i
$$

### Доказательство

$$
\begin{aligned}
x, y \in H \\
||x - \lambda y||^2 = (x - \lambda y, x - \lambda y) \geq 0 \\
(x, x) - 2\lambda (x, y) + \lambda^2 (y, y) \geq 0 \\
\lambda^2 ||y||^2 - 2\lambda (x, y) + ||x||^2 \geq 0 \\
\end{aligned}
$$

$$
\begin{aligned}
D = 4(x, y)^2 - 4(x, x)(y, y) \leq 0 \\
(x, y)^2 \leq (x, x)(y, y)
\end{aligned}
$$

### Следствие

$||x||^2 = (x, x)$ удовлетворяет неравенству треугольника.

#### Доказательство

$$
\begin{aligned}
||x + y||^2 = (x + y, x + y) = (x, x) + 2(x, y) + (y, y) \leq ||x||^2 + 2||x|| \cdot ||y|| + ||y||^2
\end{aligned}
$$

### Задача 1

Равенство паралелограмма:

$$
||x + y||^2 + ||x - y||^2 = 2||x||^2 + 2||y||^2
$$

### Задача 2

В $C[0, 1]$ нет скалярного произведения. (Используй неравенство паралелограмма)

#### Решение

Построим пример:

Выберем $f(x), g(x)$, такие что

$$
max |f(x) + g(x)| ^ 2 + max |f(x) - g(x)| ^ 2 \neq 2 \cdot max |f(x)|^2 + 2 \cdot max |g(x)|^2
$$

Пример:

::: {.callout-warning}
Добавить пример
:::

### Эпсилон сеть

### Всюду плотное множество

$A$ — всюду плотное множество в $X$, если

$$
\forall x \exists a_n \in A: ||a_n - x|| \rightarrow 0, \quad n \rightarrow \infty
$$

### Примеры

1. $\mathbb{R}, \mathbb{Q}$
2. $C[0, 1], \mathbfcal{P} = \{\sum_{n=1}^m a_n x^n\}$
3. $L^p[a, b]$

::: {.callout-info}
 Дальше было определение равномощных множеств и диагональное доказательство равномощности N и Q, я думаю вы это и так знаете
:::

::: {.callout-warning}
Было что-то важное про счетное множество, но я не успел записать
:::
