---
date: 2025-02-20
title: Нормы линейных операторов
---

$X$ — линейное пространство.
$||x||$ — норма в $X$.

$A: X \rightarrow Y$ — линейный оператор

## Ограниченность

$A$ называется ограниченным, если

$$
\exists M \forall x: ||x|| \leq 1 \Rightarrow ||Ax|| \leq M
$$

## Непрерывность

$A$ называется непрерывным, если

$$
\forall x_n — \text{последовательностей} \in X: x_n \rightarrow x_0 \Rightarrow Ax_n \rightarrow Ax_0
$$

## Теорема об эквивалентности ограниченности и непрерывности

$A$ — линейный оператор.

$A$ ограничен $\Leftrightarrow$ $A$ непрерывен.

### Доказательство

#### А ограничен $\Rightarrow$ A непрерывен

Пусть $A$ не непрерывен:

$$
\exists x_n \rightarrow 0 \forall Ax_n \nrightarrow 0
\exists \delta > 0 \forall N \exists n > N: ||Ax_n|| > \delta
$$

::: {.callout-warning}
Котыч всё стёр, я не успел записать
:::

#### A непрерывен $\Rightarrow$ A ограничен

Пусть $A$ не ограничен:

$$
\exists x_n: ||x_n|| \eq 1, ||Ax_n|| \rightarrow \infty
$$

Построим последовательность $y_n$

$$
y_n = \frac{x_n}{||Ax_n||} \rightarrow 0
$$

$$
||Ay_n|| = \frac{||Ax_n||}{||Ax_n||} = 1
$$

## Норма оператора

$$
||A|| = \sup {||Ax||: ||x|| \leq 1}
$$

### Как найти норму оператора

1) Определить верхнюю границу. Найти такое $M$, что
$$
||A|| \leq M
$$

2) Предъявить такой $x_*: ||x_* = 1||$, что эта граница достигается.

$$
\exists x_*: ||x_*|| = 1, ||Ax_*|| = M
$$

### Примеры

$$
A: l_n^p  \rightarrow l_n^p_1
$$

#### $p = \infty$

$$
\begin{aligned}
& ||x||_\infty = \max |x_n| \\
& A = (a_{k,j})_{k,j=1}^n \\
& Ax= (\sum_{j=1}^n a_{k,j}x_j)_{k=1}^n \\
& ||Ax|| = \max_{k} |\sum_{j=1}^n a_ij x_j| \leq \sum_{j=1}^n |a_{k,j}||x_j| \leq \max_{k} \sum_{j=1}^n |a_{k,j}||x_j| = \max_{k} \sum_{j=1}^n |a_{k,j}| \cdot \max_{j} |x_j| = |M \cdot ||x||
\end{aligned}
$$

Найдем $x_*$
$$
\begin{aligned}
& M = \sum_{j=1}^n |a_{k,j}| \\
& x_* = (sign a_{k,j})_{k=1}^n \\
& ||x_*|| = 1 \\
& ||Ax_*|| = \max_{k} \sum_{j=1}^n |a_{k,j}| = M
\end{aligned}
$$

Таким образом, $||A||$ в пространстве $l_n^\infty$ равна максимуму среди сумм модулей элементов строк.

#### $p = 1$

$$
\begin{aligned}
& ||x||_1 = \sum_{j=1}^n |x_j| \\
& ||Ax||_1 = \sum_{k=1}^n |\sum_{j=1}^n a_{k,j}x_j| \leq \sum_{k=1}^n \sum_{j=1}^n |a_{k,j}||x_j| = \sum_{j=1}^n |x_j| \sum_{k=1}^n |a_{k,j}| = ||x||_1 \sum_{k=1}^n |a_{k,j}| \leq M \cdot ||x||_1 \\
& M = \max_{j} \sum_{k=1}^n |a_{k,j}|
\end{aligned}
$$

Найдем $x_*$

::: {.callout-warning}
Дописать

#### $p = 2$

$$
||x||_2 = (\sum_{j=1}^n |x_j|^2)^{1/2}
$$

$A$ - самосопряженный оператор (эрмитов)^[A- самосопряженный оператор, если $(Ax, y) = (x, Ay)$].

${e_n}$ - ортонормированный базис.

$$
& A e_n = \lambda_n e_n, \quad \lambda_n in \mathbb{R} \\
$$

$$
\begin{aligned}
& x = \sum_{k=1}^\n \alpha_k e_k \\
& ||x||^2 = \sum \alpha_k^2 \\
& ||Ax|| = ||\sum \alpha_k \lambda_k e_k|| \leq |\lambda_k^*| \sum \alpha_k^2 = ||x|| \cdot ||\lambda_k^*||
& |\lambda_k^*| = \max |\lambda_k|
& M = |\lambda_k^*| = \max |\lambda_k|
\end{aligned}
$$

Найдем $x_*$

$$
\begin{aligned}
& x_* = e_k \\
& ||x_*|| = 1 \\
& ||Ax_*|| = |\lambda_k^*| = M
\end{aligned}
$$

##### Если $A$ - не самосопряженный оператора

###### Сопряженный оператор

Опр. $A^*$ - сопряженный оператор, если $(Ax, y) = (x, A^*y)$

###### Свойства сопряжения

1) $(A B)^* = B^* A^*$
2) $(A^*)^* = A$

###### Следствия

1) $||A^* A||$ - самосопряженный оператор
2) $(A^* Ax, x) \leq 0$
   
-------

$B = A^* A$ - союзная матрица для $A$

$B$ - самосопряженный оператор

B - положительно определенный оператор

Пусть $d_n$ - собственные вектора $B$, $\Lambda_n$ - собственные значения

$$
\begin{aligned}
& B d_n = \Lambda_n d_n \\
& \Lambda_n \geq 0
& \Lambda_1 \geq \Lambda_2 \geq \Lambda_3 \geq \ldots \geq 0
\end{aligned}
$$

$||A|| = \sqrt{\Lambda_1}$ — сингулярное число оператора $A$.


$$
\begin{aligned}
& ||Ax||^2 = (Ax, Ax) = (A^* A x, x) = (Bx, x) = \sum \Lambda_n |\alpha_n|^2 \leq \Lambda_1 \sum |\alpha_n|^2 = \Lambda_1 ||x||^2 \\
& ||A|| = \sqrt{\Lambda_1}
$$

### Замечания

1)
Пусть $A$ - самосопряженный оператор и все собственные значения $\lambda_n > 0$.

$\lambda$ - собственное значение $A$ $\Rightarrow$ $\frac{1}{\lambda}$ - собственное значение $A^{-1}$.

Тогда норма обратного оператора $A^{-1}$ равна $\frac{1}{\sqrt{\lambda_n}}$.

2)
$l^2$ - гильбертово пространство.
