---
date: 2025-02-14
title: Линейные нормированные пространства. Норма. Примеры.
---

## Пример. Ряды Фурье в $L^2[-\pi, \pi]$.

$L^2[-\pi, \pi]$ - пространство функций на отрезке $[-\pi, \pi]$, такие что

$$
\int_{-\pi}^{\pi} |f(x)|^2 dx < \infty.
$$

## Линейное пространство.

$X$ — линейное пространство,если

$$
x, y \in X \Rightarrow x + y \in X, \quad \alpha x \in X.
$$

## Норма

Норма в $X$: $||X|| \rightarrow \mathbb{C}\ (\mathbb{R})$

1.  $||k\cdot x|| = |k|\cdot ||x||, \quad k \in \mathbb{C}\ (\mathbb{R})$
2.  $|| x + y || \leq ||x|| + ||y||$
3.  $||x|| \geq 0, \quad ||x|| = 0 \Leftrightarrow x = 0$

## Зачем нам нужна норма?

Используя норму, мы можем определить расстояние между элементами пространства, а также сходимость последовательностей.

## Предел последовательности в линейном нормированном пространстве

$x_n \in X$ — последовательность элементов пространства $X$.

$x_n \rightarrow x$, если $||x_n - x|| \rightarrow 0$ при $n \rightarrow \infty$.

## Полное пространство

Пространство $X$ называется полным, если в нем существует предел для любой фундаментальной последовательности.

Или

$X$ — полное, если $$
x_n \in X, \quad x_n \rightarrow x_0 \Rightarrow x_0 \in X.
$$

## Фундаментальная последовость

$x_n \in X$ — фундаментальная последовательность, если

$$
\forall \varepsilon > 0 \quad \exists N: \forall n, m > N \quad ||x_n - x_m|| < \varepsilon.
$$

## Теорема сходимости в полном пространстве

$$
x_n \text{ сходится} \Leftrightarrow x_n \text{ фундаментальна}.
$$

::: {.callout-warning}
TODO: Добавить больше примеров пространств. 
:::

::: {.callout-warning}
TODO: Добавить эквивалентные нормы.
:::

::: {.callout-warning}
TODO: Добавить шары и норму Минковского.
:::